spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka
          auto-create-topics: true
      bindings:
        output:
          destination: exchanger-standard
          content-type: application/json
        input:
          destination: exchanger-standard
          content-type: application/json
          group: testGroup
      default-binder: kafka

cloud:
  streams:
    enabled: true
